databases:
  - name: predictorapp
    databaseName: heatpreddb_x3og
    user: william

services:
  - type: web
    name: predictorapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn predictorapp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: heatpredapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4